# -*- coding: utf-8 -*-
"""final_last.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pTYnEM0jL_j5ln6uRqwhGdm-W643RQUl
"""

import json
# Path is used to create folders and file paths.
from pathlib import Path
# json is used to save our results in JSON format.
import json
# joblib is used to save the trained ML model.
import joblib
# NumPy is used for numerical operations.
import numpy as np
# Pandas is used for data analysis.
import pandas as pd
# ColumnTransformer allows us to apply different
# preprocessing to numerical and categorical columns.
from sklearn.compose import ColumnTransformer
# Random Forest model.
from sklearn.ensemble import RandomForestClassifier
# Used to calculate permutation importance.
from sklearn.inspection import permutation_importance
# Logistic Regression model.
from sklearn.linear_model import LogisticRegression
# Evaluation metrics.
from sklearn.metrics import (accuracy_score, f1_score, precision_score,
                             recall_score,
                             roc_auc_score)
# GridSearchCV is used for hyperparameter tuning.
from sklearn.model_selection import ( GridSearchCV,
    StratifiedKFold,
    train_test_split
)
# Pipeline connects preprocessing and model together.
from sklearn.pipeline import Pipeline
# Used for encoding and scaling.
from sklearn.preprocessing import (OneHotEncoder,
                                  StandardScaler)
# Used for filling missing values.
from sklearn.impute import SimpleImputer
# Simple baseline model.
from sklearn.dummy               import DummyClassifier
from sklearn.linear_model        import LogisticRegression
from sklearn.ensemble            import RandomForestClassifier
import matplotlib.pyplot as plt

RANDOM_STATE = 42
DATA_PATH = "/content/sample_data/orders_dataset.csv"
MODEL_PATH = Path("models/return_risk_model.pkl")
REPORT_PATH = Path("reports/part1_results.json")

def load_data():
    return pd.read_csv(DATA_PATH)

print('\n... Project structure created...')

#2.Verify the generated data.

#Report: total row count, overall return rate, percentage of missing rating_given values,
# and a table of return rate broken out by product_category
# and separately by payment_method.
# State explicitly whether the missingness pattern in
# rating_given looks like MCAR, MAR, or MNAR

df = load_data() # Load data for initial verification

# 1. Basic dataset verification
print("Dataset shape:", df.shape)
print("Total rows:", len(df))
print("Total columns:", len(df.columns))

# 2. Overall return rate
overall_return_rate = df["returned"].mean() * 100

print("\nOverall return rate:")
print(f"{overall_return_rate:.2f}%")

# 3. Missing rating_given
missing_rating_pct = df["rating_given"].isna().mean() * 100

print("\nMissing rating_given:")
print(f"{missing_rating_pct:.2f}%")

# 4. Missing rating by payment method
#    This helps determine MCAR / MAR / MNAR
missing_by_payment = (
    df.groupby("payment_method")["rating_given"]
    .apply(lambda x: x.isna().mean() * 100)
    .reset_index(name="missing_rating_pct")
)

print("\nMissing rating percentage by payment method:")
print(missing_by_payment)

# 5. Return rate by product category
return_by_category = (
    df.groupby("product_category")["returned"]
    .agg(
        orders="count",
        returned_orders="sum",
        return_rate="mean"
    )
    .reset_index()
)

return_by_category["return_rate"] *= 100

print("\nReturn rate by product category:")
print(return_by_category)

# 6. Return rate by payment method
return_by_payment = (
    df.groupby("payment_method")["returned"]
    .agg(
        orders="count",
        returned_orders="sum",
        return_rate="mean"
    )
    .reset_index()
)

return_by_payment["return_rate"] *= 100

print("\nReturn rate by payment method:")
print(return_by_payment)

# 7. MAR / MCAR / MNAR conclusion
cod_missing = df.loc[
    df["payment_method"] == "COD",
    "rating_given"
].isna().mean() * 100

non_cod_missing = df.loc[
    df["payment_method"] != "COD",
    "rating_given"
].isna().mean() * 100

gap = cod_missing - non_cod_missing

print("\nMissingness analysis:")
print(f"COD missing rate: {cod_missing:.2f}%")
print(f"Non-COD missing rate: {non_cod_missing:.2f}%")
print(f"Missing-rate gap: {gap:.2f} percentage points")

print("\nConclusion: MAR")

print(
    "Reason: rating_given missingness depends on the observed "
    "payment_method column. The generator assigns approximately "
    "22% missingness probability to COD orders and 6% to non-COD "
    "orders. Therefore the missingness is not MCAR. It is also "
    "not MNAR because the missingness mechanism does not depend "
    "on the unobserved rating_given value itself."
)

"""**Preprocess without leakage**. Using a ColumnTransformer + Pipeline (scikit-learn), impute missing numeric values with the median and missing categorical values with the mode, one-hot encode product_category and payment_method, and standard-scale the numeric features. Fit the pipeline on the training split only, then transform both splits -- never fit on the test split

"""

# EDA - EXPLORATORY DATA ANALYSIS


print("=" * 60)
print("EDA - FLIPKART ORDER DATASET")
print("=" * 60)

# 1. Basic information
print("\nDataset shape:", df.shape)
print("\nFirst 5 rows:", df.head())
print("\nColumn names:", df.columns.tolist())
print("\nData types:", df.dtypes)
print("\nMissing values:", df.isnull().sum())

# 2. Missing values
print("\nMissing values:")
print(df.isnull().sum())

print("\nMissing percentage:")
print((df.isnull().mean() * 100).round(2))

# 3. Target variable - returned
print("\nReturned value counts:")
print(df["returned"].value_counts())

print("\nReturn percentage:")
print((df["returned"].value_counts(normalize=True) * 100).round(2))

# 4. Return rate by product category
category_return = (
    df.groupby("product_category")["returned"]
    .mean()
    .sort_values(ascending=False) * 100
)

print("\nReturn rate by product category:")
print(category_return.round(2))

# 5. Return rate by payment method
payment_return = (
    df.groupby("payment_method")["returned"]
    .mean()
    .sort_values(ascending=False) * 100
)

print("\nReturn rate by payment method:")
print(payment_return.round(2))

# 6. Average price by return status
print("\nAverage price by return status:")
print(df.groupby("returned")["price_inr"].mean().round(2))

# 7. Average discount by return status
print("\nAverage discount by return status:")
print(df.groupby("returned")["discount_pct"].mean().round(2))


# EDA GRAPHS
# ============================================================

# Graph 1 - Returned vs Not Returned
# ------------------------------------------------------------

return_counts = df["returned"].value_counts().sort_index()

plt.figure(figsize=(6, 4))
plt.bar(["Not Returned", "Returned"], return_counts.values)

plt.title("Returned vs Not Returned Orders")
plt.xlabel("Order Status")
plt.ylabel("Number of Orders")

plt.tight_layout()
plt.show()

# Graph 2 - Return Rate by Product Category
# ------------------------------------------------------------

plt.figure(figsize=(7, 4))

plt.bar(
    category_return.index,
    category_return.values
)

plt.title("Return Rate by Product Category")
plt.xlabel("Product Category")
plt.ylabel("Return Rate (%)")
plt.xticks(rotation=30)
plt.tight_layout()
plt.show()

# Graph 3 - Return Rate by Payment Method
# ------------------------------------------------------------

plt.figure(figsize=(7, 4))

plt.bar(payment_return.index, payment_return.values)

plt.title("Return Rate by Payment Method")
plt.xlabel("Payment Method")
plt.ylabel("Return Rate (%)")
plt.xticks(rotation=20)
plt.tight_layout()
plt.show()

# Graph 4 - Price Distribution
# ------------------------------------------------------------

plt.figure(figsize=(7, 4))

plt.hist(df["price_inr"].dropna(), bins=30)
plt.title("Distribution of Order Price")
plt.xlabel("Price (INR)")
plt.ylabel("Number of Orders")
plt.tight_layout()
plt.show()

# Graph 5 - Missing Rating by Payment Method
# ------------------------------------------------------------

missing_rating = (
    df.groupby("payment_method")["rating_given"]
    .apply(lambda x: x.isna().mean() * 100)
)

plt.figure(figsize=(7, 4))
plt.bar(missing_rating.index, missing_rating.values)

plt.title("Missing Rating Percentage by Payment Method")
plt.xlabel("Payment Method")
plt.ylabel("Missing Rating (%)")
plt.xticks(rotation=20)
plt.tight_layout()
plt.show()

# Preprocessing without leakage #

# 1. Load dataset
df = pd.read_csv("/content/sample_data/orders_dataset.csv")

# 2. Separate features and target
X = df.drop("returned", axis=1)
y = df["returned"]

# 3. Remove order_id
X = X.drop("order_id", axis=1)

# 4. Define numerical columns
numeric_features = [
    "price_inr",
    "discount_pct",
    "customer_tenure_days",
    "num_previous_orders",
    "num_previous_returns",
    "delivery_distance_km",
    "delivery_days",
    "is_weekend_order",
    "rating_given"
]

# 5. Define categorical columns
categorical_features = [
    "product_category",
    "payment_method"
]

# 6. Numerical preprocessing
numeric_pipeline = Pipeline(
    steps=[("imputer", SimpleImputer(strategy="median")),
           ("scaler", StandardScaler())
           ])

# 7. Categorical preprocessing
categorical_pipeline = Pipeline(
    steps=[("imputer",SimpleImputer(strategy="most_frequent")),
           ("onehot", OneHotEncoder(handle_unknown="ignore"))
          ])

# 8. Combine both pipelines
preprocessor = ColumnTransformer(
    transformers=[
        ("numeric", numeric_pipeline, numeric_features),
        ("categorical", categorical_pipeline, categorical_features)
    ]
)

# 9. Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20,
                                                    random_state=42, stratify=y)

# 10. Fit preprocessing ONLY on training data
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

# 11. Print information
print("Original dataset:", X.shape)
print()
print("Training data:", X_train.shape)
print()
print("Testing data:", X_test.shape)
print()
print("Processed training data shape:", X_train_processed.shape)
print()
print("Processed testing data shape:", X_test_processed.shape)
print()

""" 	Build a baseline. Train a DummyClassifier  on a stratified 80/20 train/test split (random_state=42). Report its accuracy and its F1-score for the returned=1 class
---
## Step 5 — Baseline Model

The baseline is the **dumbest possible model** that still makes predictions.
Every subsequent model must beat it — otherwise training has learned nothing.

**Strategy `most_frequent`:** Always predict the class that appeared most
 often in training. For this dataset, that means predicting
 `0` (No attrition) for every single employee.
"""
# ------------------------------------------------------------
# Train and evaluate baseline model
# ------------------------------------------------------------

def run_dummy_classifier(X_train, X_test, y_train, y_test, preprocessor):
    # Create the DummyClassifier
    dummy_model = Pipeline(steps=[
            ("preprocessor", preprocessor),
            ("classifier",DummyClassifier(strategy="most_frequent"))
              ])

    # Train the model
    dummy_model.fit(X_train, y_train)

    # Make predictions
    y_pred = dummy_model.predict(X_test)

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)

    # Calculate F1-score for returned = 1
    f1 = f1_score(y_test, y_pred, pos_label=1)

    # Display results
    print("---DummyClassifier Results---")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Accuracy percentage: {accuracy * 100:.2f}%")
    print(f"F1-score for returned=1: {f1:.4f}")

    print("\nInterpretation:")
    print(""" The DummyClassifier predicts only the majority class.
          Therefore, it can have high accuracy but zero recall
          for returned orders.""")

    return dummy_model
# ------------------------------------------------------------
# Task 5 - LOGISTIC REGRESSION + threshold sweep
# ------------------------------------------------------------


def prepare_data(df):
    X = df.drop("returned", axis=1)
    y = df["returned"]
    X = X.drop("order_id", axis=1)
    return X, y

def create_preprocessor():
    numeric_features = [
        "price_inr",
        "discount_pct",
        "customer_tenure_days",
        "num_previous_orders",
        "num_previous_returns",
        "delivery_distance_km",
        "delivery_days",
        "is_weekend_order",
        "rating_given"
    ]
    categorical_features = [
        "product_category",
        "payment_method"
    ]
    numeric_pipeline = Pipeline(
        steps=[("imputer", SimpleImputer(strategy="median")),
               ("scaler", StandardScaler())
               ])
    categorical_pipeline = Pipeline(
        steps=[("imputer",SimpleImputer(strategy="most_frequent")),
               ("onehot", OneHotEncoder(handle_unknown="ignore"))
              ])
    preprocessor = ColumnTransformer(
        transformers=[
            ("numeric", numeric_pipeline, numeric_features),
            ("categorical", categorical_pipeline, categorical_features)
              ]
   )
    return preprocessor


def split_data(X, y):
    return train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

def run_logistic_regression(X_train,X_test,
                            y_train,y_test,
                            preprocessor
                            ):

    """

    Train Logistic Regression using class_weight='balanced'.
    Because returned orders
    are less common than non-returned orders.

    At the default threshold of 0.5 we calculate:
        Accuracy
        F1
        Recall
        Precision
        ROC-AUC

    Then we sweep thresholds from 0.10 to 0.90
    using a maximum step size of 0.02.
    """

    print("\n")
    print("=" * 60)
    print("TASK 5 - LOGISTIC REGRESSION")
    print("=" * 60)

    logistic_model = Pipeline(
        steps=[
            (
                "preprocessor",
                preprocessor
            ),
            (
                "classifier",
                LogisticRegression(
                    class_weight="balanced",
                    max_iter=1000,
                    random_state=42
                )
            )
        ]
    )

    logistic_model.fit(X_train, y_train)
    y_pred = logistic_model.predict(X_test)
    y_probability = logistic_model.predict_proba(X_test)[:, 1]

    # Calculate default metrics
    accuracy = accuracy_score(y_test, y_pred)

    f1 = f1_score(y_test, y_pred, pos_label=1, zero_division=0)

    recall = recall_score(y_test, y_pred, pos_label=1, zero_division=0)

    precision = precision_score(y_test, y_pred, pos_label=1, zero_division=0)

    roc_auc = roc_auc_score(y_test, y_probability)

    print("\nDefault threshold = 0.50")

    print("Accuracy:", f"{accuracy:.4f}")
    print("F1:", f"{f1:.4f}")
    print("Recall:", f"{recall:.4f}")
    print("Precision:", f"{precision:.4f}")
    print("ROC-AUC:", f"{roc_auc:.4f}")

    # --------------------------------------------------------
    # Threshold sweep
    # --------------------------------------------------------

    threshold_results = []

    # 0.10 to 0.90 with step 0.01
    # This satisfies the requirement of at most 0.02.
    thresholds = np.arange(
        0.10,
        0.901,
        0.01
    )

    for threshold in thresholds:

        # Convert probabilities into predictions
        threshold_predictions = (
            y_probability >= threshold
        ).astype(int)

        threshold_f1 = f1_score(
            y_test,
            threshold_predictions,
            pos_label=1,
            zero_division=0
        )

        threshold_recall = recall_score(
            y_test,
            threshold_predictions,
            pos_label=1,
            zero_division=0
        )

        threshold_precision = precision_score(
            y_test,
            threshold_predictions,
            pos_label=1,
            zero_division=0
        )

        threshold_results.append({
            "threshold": threshold,
            "f1": threshold_f1,
            "recall": threshold_recall,
            "precision": threshold_precision
        })

    threshold_df = pd.DataFrame(
        threshold_results
    )

    # Find threshold with maximum F1
    best_row = threshold_df.loc[
        threshold_df["f1"].idxmax()
    ]

    best_threshold = best_row["threshold"]
    best_f1 = best_row["f1"]
    best_recall = best_row["recall"]
    best_precision = best_row["precision"]

    print("\nBest Logistic Regression threshold")
    print("----------------------------------")

    print("Threshold:", f"{best_threshold:.2f}")

    print("F1:", f"{best_f1:.4f}")

    print("Recall:", f"{best_recall:.4f}")

    print("Precision:", f"{best_precision:.4f}")

    # Recall improvement compared with default threshold
    recall_difference = (
        best_recall - recall
    )

    precision_difference = (
        best_precision - precision
    )

    print(
        "\nRecall improvement:",
        f"{recall_difference * 100:.2f}",
        "percentage points"
    )

    print(
        "Precision change:",
        f"{precision_difference * 100:.2f}",
        "percentage points"
    )

    # Save threshold results
    Path('../results').mkdir(parents=True, exist_ok=True) # Ensure results directory exists
    threshold_df.to_csv(
        "../results/logistic_threshold_results.csv",
        index=False
    )

    return logistic_model, threshold_df


# ============================================================
# 9. TASK 6 - RANDOM FOREST + GRID SEARCH
# ============================================================

def run_random_forest(
    X_train,
    X_test,
    y_train,
    y_test,
    preprocessor
):

    """
    Task 6:
    Train and tune a Random Forest.

    Required:
        class_weight='balanced'
        random_state=42

    Grid Search:
        n_estimators = [100, 200]
        max_depth = [6, 10, None]

    Evaluation:
        ROC-AUC

    Cross-validation:
        5-fold StratifiedKFold
    """

    print("\n")
    print("=" * 60)
    print("TASK 6 - RANDOM FOREST + GRID SEARCH")
    print("=" * 60)

    # Create Random Forest
    random_forest = RandomForestClassifier(
        class_weight="balanced",
        random_state=42
    )

    # Put preprocessing and Random Forest together
    rf_pipeline = Pipeline(
        steps=[("preprocessor", preprocessor),
               ("classifier", random_forest)
              ])

    # Required parameter grid
    parameter_grid = {
        "classifier__n_estimators": [100, 200],
        "classifier__max_depth": [6, 10, None]
        }

    # Five-fold stratified cross-validation
    cross_validation = StratifiedKFold(n_splits=5, shuffle=True,random_state=42)

    # GridSearchCV
    grid_search = GridSearchCV(
        estimator= rf_pipeline,
        param_grid= parameter_grid,
        scoring= "roc_auc",
        cv= cross_validation,
        n_jobs= -1,
        return_train_score= False
    )

    print("\nRunning GridSearchCV...")
    print("------------------------")

    # Train all combinations
    grid_search.fit( X_train, y_train)

    # Best model
    best_rf_model = grid_search.best_estimator_

    # Best parameters
    best_parameters = grid_search.best_params_

    # Best cross-validation score
    best_cv_roc_auc = grid_search.best_score_

    # Test probabilities
    test_probability = best_rf_model.predict_proba(X_test)[:, 1]

    # Test ROC-AUC
    test_roc_auc = roc_auc_score(y_test, test_probability)

    print("\nBest Random Forest Parameters")
    print("-----------------------------")

    print(best_parameters)

    print("\nBest cross-validated ROC-AUC:", f"{best_cv_roc_auc:.4f}")

    print("Held-out test ROC-AUC:", f"{test_roc_auc:.4f}")

    print(
        "Difference between CV and test ROC-AUC:",
        f"{abs(best_cv_roc_auc - test_roc_auc):.4f}"
    )

    # Save GridSearch results
    Path('../results').mkdir(parents=True, exist_ok=True) # Ensure results directory exists
    grid_results = pd.DataFrame(grid_search.cv_results_)

    grid_results.to_csv(
        "../results/random_forest_grid_search.csv",
        index=False)

    return best_rf_model, grid_search


# ============================================================
# 10. TASK 7 - RANDOM FOREST THRESHOLD SWEEP
# ============================================================

def find_rf_threshold(rf_model, X_test, y_test):

    """
    Task 7 / Task 9 requirement:

    Run the threshold sweep AGAIN using the Random Forest's
    own predict_proba output.

    We must NOT reuse the Logistic Regression threshold.

    The resulting threshold is t*_rf.
    """

    print("\n")
    print("=" * 60)
    print("RANDOM FOREST THRESHOLD SWEEP")
    print("=" * 60)

    # Get Random Forest probabilities
    rf_probability = rf_model.predict_proba(
        X_test
    )[:, 1]

    threshold_results = []

    # 0.10 to 0.90 with 0.01 steps
    thresholds = np.arange(
        0.10,
        0.901,
        0.01
    )

    for threshold in thresholds:

        predictions = (
            rf_probability >= threshold
        ).astype(int)

        f1 = f1_score(
            y_test,
            predictions,
            pos_label=1,
            zero_division=0
        )

        recall = recall_score(
            y_test,
            predictions,
            pos_label=1,
            zero_division=0
        )

        precision = precision_score(
            y_test,
            predictions,
            pos_label=1,
            zero_division=0
        )

        threshold_results.append({
            "threshold": threshold,
            "f1": f1,
            "recall": recall,
            "precision": precision
        })

    threshold_df = pd.DataFrame(
        threshold_results
    )

    # Find maximum F1
    best_row = threshold_df.loc[
        threshold_df["f1"].idxmax()
    ]

    t_rf = float(
        best_row["threshold"]
    )

    print("\nF1-maximising Random Forest threshold")
    print("-------------------------------------")

    print(
        "t*_rf:",
        f"{t_rf:.2f}"
    )

    print(
        "F1:",
        f"{best_row['f1']:.4f}"
    )

    print(
        "Recall:",
        f"{best_row['recall']:.4f}"
    )

    print(
        "Precision:",
        f"{best_row['precision']:.4f}"
    )

    # Save results
    Path('../results').mkdir(parents=True, exist_ok=True) # Ensure results directory exists
    threshold_df.to_csv(
        "../results/random_forest_threshold_results.csv",
        index=False
    )

    return t_rf, threshold_df


# ============================================================
# 11. TASK 7 - FEATURE IMPORTANCE
# ============================================================

def analyze_feature_importance(
    rf_model,
    X_test,
    y_test
):

    """
    Task 7:

    Extract Random Forest impurity-based feature importance.

    Then calculate permutation importance on the held-out
    test set.

     """

    print("\n")
    print("=" * 60)
    print("TASK 7 - FEATURE IMPORTANCE")
    print("=" * 60)

    # Get the preprocessing step
    fitted_preprocessor = rf_model.named_steps["preprocessor"]

    # Get the Random Forest
    fitted_rf = rf_model.named_steps["classifier"]

    # Get feature names after preprocessing
    feature_names = fitted_preprocessor.get_feature_names_out()

    # Get impurity-based feature importance
    impurity_importance = fitted_rf.feature_importances_

    # Create a DataFrame
    importance_df = pd.DataFrame({
        "feature": feature_names,
        "importance": impurity_importance
    })

    # Sort from highest to lowest
    importance_df = importance_df.sort_values(
        "importance",
        ascending=False
    )

    # Top 5 transformed features
    top_5 = importance_df.head(5).copy()

    print("\nTop 5 impurity-based features:")
    print(top_5.to_string(index=False))

    # --------------------------------------------------------
    # Map transformed features back to original features
    # --------------------------------------------------------

    def get_original_feature(feature_name):

        if feature_name.startswith("numeric__"):
            return feature_name.replace(
                "numeric__",
                ""
            )

        if feature_name.startswith("categorical__"):
            categorical_name = feature_name.replace(
                "categorical__","")

            if categorical_name.startswith("product_category_"):
                     return "product_category"

            if categorical_name.startswith("payment_method_"):
                     return "payment_method"

        return feature_name

    top_5["original_feature"] = (
        top_5["feature"]
        .apply(get_original_feature)
    )

    print("\nTop 5 with original feature names:")
    print(top_5.to_string(index=False))


    # --------------------------------------------------------
    # Permutation importance
    # --------------------------------------------------------
    #
    # Important:
    # We pass the ORIGINAL X_test to the complete pipeline.
    # The pipeline handles preprocessing internally.
    #
    # Therefore permutation importance measures the effect
    # of shuffling an original input feature.
    # --------------------------------------------------------

    permutation_result = permutation_importance(
        rf_model,
        X_test,
        y_test,
        scoring="roc_auc",
        n_repeats=10,
        random_state=42,
        n_jobs=-1
    )

    permutation_df = pd.DataFrame({
        "feature": X_test.columns,
        "permutation_importance": (
            permutation_result.importances_mean
        )
    })

    permutation_df = permutation_df.sort_values(
        "permutation_importance",
        ascending=False
    )

    print("\nPermutation importance:")
    print(permutation_df.to_string(index=False))

    # --------------------------------------------------------
    # Compare original top-5 features
    # --------------------------------------------------------

    original_top_features = (
        top_5["original_feature"]
        .drop_duplicates()
        .tolist()
    )

    comparison_rows = []

    for feature in original_top_features:

        # Total impurity importance belonging to
        # this original feature
        impurity_value = (
            importance_df[
                importance_df["feature"].apply(
                    get_original_feature
                ) == feature
            ]["importance"]
            .sum()
        )

        # Permutation importance for the original feature
        permutation_matches = permutation_df[
            permutation_df["feature"] == feature
        ]

        if len(permutation_matches) > 0:
            permutation_value = (
                permutation_matches[
                    "permutation_importance"
                ].iloc[0]
            )
        else:
            permutation_value = np.nan

        comparison_rows.append({
            "feature": feature,
            "impurity_importance": impurity_value,
            "permutation_importance": permutation_value
        })

    comparison_df = pd.DataFrame(
        comparison_rows
    )

    comparison_df = comparison_df.sort_values(
        "impurity_importance",
        ascending=False
    )

    print("\nImpurity vs permutation comparison:")
    print(comparison_df.to_string(index=False))

    # Save results
    Path('../results').mkdir(parents=True, exist_ok=True) # Ensure results directory exists
    importance_df.to_csv(
        "../results/random_forest_feature_importance.csv",
        index=False
    )

    permutation_df.to_csv(
        "../results/random_forest_permutation_importance.csv",
        index=False
    )

    comparison_df.to_csv(
        "../results/importance_comparison.csv",
        index=False
    )

    return (
        importance_df,
        permutation_df,
        comparison_df
    )


# ============================================================
# 12. TASK 8 - SUBGROUP ANALYSIS
# ============================================================

def subgroup_analysis(
    rf_model,
    X_test,
    y_test,
    t_rf
):

    """
    Task 8:

    Calculate recall and precision separately for:

        1. product_category
        2. payment_method

    We use t*_rf, the F1-maximising Random Forest threshold.
    """

    print("\n")
    print("=" * 60)
    print("TASK 8 - SUBGROUP / ROOT-CAUSE ANALYSIS")
    print("=" * 60)

    # Get probabilities
    probabilities = rf_model.predict_proba(X_test)[:, 1]

    # Apply Random Forest threshold
    predictions = (probabilities >= t_rf).astype(int)

    # Make a copy of test data
    subgroup_data = X_test.copy()

    subgroup_data["actual"] = (y_test.values)

    subgroup_data["prediction"] = predictions

    # Product category
    # --------------------------------------------------------

    category_results = []

    for category in sorted(subgroup_data["product_category"].unique()):
        subset = subgroup_data[
            subgroup_data["product_category"]
            == category
        ]

        category_recall = recall_score(
            subset["actual"],
            subset["prediction"],
            pos_label=1,
            zero_division=0
        )

        category_precision = precision_score(
            subset["actual"],
            subset["prediction"],
            pos_label=1,
            zero_division=0
        )

        category_results.append({
            "product_category": category,
            "orders": len(subset),
            "recall": category_recall,
            "precision": category_precision
        })

    category_df = pd.DataFrame(category_results)


    print("\nPerformance by product category:")
    print(category_df.to_string(index=False))

    # Payment method
    # --------------------------------------------------------

    payment_results = []

    for payment in sorted(
        subgroup_data["payment_method"].unique()
    ):

        subset = subgroup_data[
            subgroup_data["payment_method"]
            == payment
        ]

        payment_recall = recall_score(
            subset["actual"],
            subset["prediction"],
            pos_label=1,
            zero_division=0
        )

        payment_precision = precision_score(
            subset["actual"],
            subset["prediction"],
            pos_label=1,
            zero_division=0
        )

        payment_results.append({
            "payment_method": payment,
            "orders": len(subset),
            "recall": payment_recall,
            "precision": payment_precision
        })

    payment_df = pd.DataFrame(payment_results)

    print("\nPerformance by payment method:")
    print(payment_df.to_string(index=False))


    # Overall performance at t*_rf
    # --------------------------------------------------------

    overall_recall = recall_score(
        y_test,
        predictions,
        pos_label=1,
        zero_division=0
    )

    overall_precision = precision_score(
        y_test,
        predictions,
        pos_label=1,
        zero_division=0
    )

    print("\nOverall Random Forest performance at t*_rf:")
    print("Recall:",f"{overall_recall:.4f}")

    print("Precision:", f"{overall_precision:.4f}")



    # Save subgroup results
    Path('../results').mkdir(parents=True, exist_ok=True) # Ensure results directory exists
    category_df.to_csv(
        "../results/subgroup_product_category.csv",
        index=False
    )

    payment_df.to_csv(
        "../results/subgroup_payment_method.csv",
        index=False
    )

    return category_df, payment_df


# ============================================================
# 13. TASK 9 - SAVE FINAL MODEL
# ============================================================

def save_final_model(rf_model, t_rf):

    """
    Task 9:

    Save the final tuned Random Forest pipeline.

    """

    print("\n")
    print("=" * 60)
    print("TASK 9 - SAVE FINAL MODEL")
    print("=" * 60)

    # Save the complete pipeline
    joblib.dump(rf_model, MODEL_PATH)

    print(
        "Model saved to:",
        MODEL_PATH
    )

    # Save the Random Forest threshold
    threshold_path = (
        MODEL_PATH.parent / "return_risk_threshold.json"
    )

    threshold_data = {"t_rf": t_rf}

    with open(threshold_path, "w") as file:
        json.dump(threshold_data, file, indent=4)

    print("Random Forest threshold saved:", threshold_path)

    print(
        "Model saved to:",
        MODEL_PATH
    )

    print(
        "Random Forest threshold saved to:",
        threshold_path
    )

    print(
        "t*_rf:",
        f"{t_rf:.2f}"
    )


# ============================================================
# 14. VERIFY SAVED MODEL
# ============================================================

def verify_saved_model(X_test, rf_model):

    """
    Verify that the saved model can be loaded successfully.

    Also verify that predict_proba() works.
    """

    print("\n")
    print("=" * 60)
    print("VERIFY SAVED MODEL")
    print("=" * 60)

    loaded_model = joblib.load(MODEL_PATH)

    probabilities = loaded_model.predict_proba(X_test)[:, 1]


    print("Model loaded successfully.")

    print("Number of probability predictions:", len(probabilities))

    print("predict_proba() is working correctly.")

    return loaded_model


# ============================================================
# 15. MAIN PROGRAM
# ============================================================

def main():

    """
    Run all Part 1 tasks in order.
    """

    # Create necessary directories if they don't exist
    Path('../results').mkdir(parents=True, exist_ok=True)
    MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)

    # --------------------------------------------------------
    # Load data
    # --------------------------------------------------------

    df = load_data()

    # --------------------------------------------------------
    # Prepare X and y
    # --------------------------------------------------------

    X, y = prepare_data(df)

    # --------------------------------------------------------
    # Create preprocessing
    # --------------------------------------------------------

    preprocessor = create_preprocessor()

    # --------------------------------------------------------
    # Train/test split
    # --------------------------------------------------------

    X_train, X_test, y_train, y_test = split_data(X, y)

    # --------------------------------------------------------
    # TASK 4
    # DummyClassifier
    # --------------------------------------------------------

    dummy_model = run_dummy_classifier(
        X_train,
        X_test,
        y_train,
        y_test,
        preprocessor
    )

    # --------------------------------------------------------
    # TASK 5
    # Logistic Regression
    # --------------------------------------------------------

    logistic_model, logistic_threshold_results = (
        run_logistic_regression(
            X_train,
            X_test,
            y_train,
            y_test,
            preprocessor
        )
    )

    # --------------------------------------------------------
    # TASK 6
    # Random Forest + GridSearchCV
    # --------------------------------------------------------

    best_rf_model, grid_search = (
        run_random_forest(
            X_train,
            X_test,
            y_train,
            y_test,
            preprocessor
        )
    )

    # --------------------------------------------------------
    # TASK 7 / TASK 9
    # Random Forest threshold
    # --------------------------------------------------------

    t_rf, rf_threshold_results = find_rf_threshold(
        best_rf_model,
        X_test,
        y_test
    )

    # --------------------------------------------------------
    # TASK 7
    # Feature importance
    # --------------------------------------------------------

    (
        importance_df,
        permutation_df,
        comparison_df
    ) = analyze_feature_importance(
        best_rf_model,
        X_test,
        y_test
    )

    # --------------------------------------------------------
    # TASK 8
    # Subgroup analysis
    # --------------------------------------------------------

    category_df, payment_df = subgroup_analysis(
        best_rf_model,
        X_test,
        y_test,
        t_rf
    )

    # --------------------------------------------------------
    # TASK 9
    # Save final model
    # --------------------------------------------------------

    save_final_model(best_rf_model, t_rf)

    # --------------------------------------------------------
    # Verify saved model
    # --------------------------------------------------------

    loaded_model = verify_saved_model(X_test, best_rf_model)

    # --------------------------------------------------------
    # Final message
    # --------------------------------------------------------

    print("\n")
    print("=" * 60)
    print("PART 1 COMPLETE")
    print("=" * 60)

    print("\nFinal artifact:")

    print("models/return_risk_model.pkl")

    print("\nRandom Forest threshold t*_rf:", f"{t_rf:.2f}")

    print("\nThis saved model will be used by Part 3.")

# ============================================================
# 16. RUN PROGRAM
# ============================================================

if __name__ == "__main__":
    main()